
spring:
  profiles:
    active:
      - test
  datasource:
    url: jdbc:h2:file:~/h2/book-store-test
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

